project:
  type: book
  output-dir: docs

page-navigation: false

book:
  title: "R for Data Science"
  subtitle: "Enhancement Class at The Bedford Sixth Form"
  author: "Andrea Carpignani"
  date: today
  date-format: "DD MMMM YYYY"
  
  page-footer:
    left: |
      A. Carpignani -- R for Data Science
    right: |
      This book was build with <a href="https://quarto.org/">Quarto</a>.
  
  site-url: "https://acarpignani.github.io/notebook/"
  repo-url: "https://github.com/acarpignani/notebook/"
  repo-branch: main
  
  chapters:
    - index.qmd
    
    - part: "R programming"
      chapters:
        - r-basics.qmd
        - vectors.qmd
        - matrices.qmd
        - lists.qmd
        - data-frames.qmd
        - in-and-out.qmd

    - part: "Advanced R programming"
      chapters:
        - conditionals.qmd
        - loops.qmd
        - functions.qmd
        - purrr-functions.qmd
    
    - part: "Data manipulation"
      chapters:
        - dplyr.qmd
        - tidyr.qmd
    
    - part: "Data Visualisation"
      chapters:
        - intro-gg.qmd
        - ggplot-basics.qmd
        - core-ggplot.qmd
        - advanced-ggplot.qmd
        
    - part: "Practice"
      chapters:
        - practice-basics.qmd
        - practice-matrices.qmd
        - practice-data-frames.qmd
        - practice-control-flow.qmd
        - practice-functions.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: false
    html-math-method: katex
    number-depth: 2
    code-link: true


editor: visual

