project:
  type: website
  output-dir: docs

page-navigation: true

website:
  title: "R for Data Science"
  navbar:
    search: true
    left:
        - text: "Introduction"
          file: index.qmd
        - r-basics.qmd
        - vectors.qmd
        - data-frames.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    html-math-method: katex

editor: visual
        
date-format: "DD MMMM YYYY"

