project:
  type: website
  output-dir: docs

page-navigation: false

website:
  title: "R for Data Science"
  
  navbar:
    search: false
    tools:
      - icon: github
        menu:
          - text: "Source code"
            url: "https://github.com/acarpignani/notebook"
          - text: "Report a bug"
            url: "https://github.com/acarpignani/notebook/issues"
    
    left: 
      - text: "Intro"
        file: index.qmd
      - text: "R programming"
        file: r-programming.qmd
      - text: "Intro to ML"
        file: intro-ml.qmd
      - text: "Practice"
        file: practice-basics.qmd
  
  sidebar:
    
    - title: "R programming"
      style: "floating"
      search: false
      collapse-level: 1

      contents:
        - section: "Introduction to R programming"
          contents:
            - text: "Introduction"
              file: r-programming.qmd
            - r-basics.qmd
            - vectors.qmd
            - matrices.qmd
            - lists.qmd
            - data-frames.qmd
            - in-and-out.qmd
        
        - section: "Basic R Programming"
          contents:
            - conditionals.qmd
            - loops.qmd
            - functions.qmd
            - purrr-functions.qmd

        - section: "Data Manipulation"
          contents:
            - dplyr.qmd
            - tidyr.qmd
            
        - section: "Data Visualisation"
          contents:
            - intro-gg.qmd
            - ggplot-basics.qmd
            - themes.qmd


    - title: "Practice"
      contents:
        - practice-basics.qmd
        - practice-matrices.qmd
        - practice-data-frames.qmd
        - practice-control-flow.qmd
        - practice-functions.qmd
        

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    html-math-method: katex

editor: visual
        
date-format: "DD MMMM YYYY"

