project:
  type: website

website:
  page-navigation: true
  navbar:
    search: true
    left:
        - text: "R for Data Science"
          file: index.qmd
        - text: "Introduction to R"
          file: 01-r-basics.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: false
    html-math-method: katex

editor: visual
        
date-format: "DD MMMM YYYY"

