# Practice 3: Data Frames {.unnumbered}

The datasets for this practice can be found [here](https://github.com/acarpignani/notebook/tree/main/datasets). To answer the questions you are expected to load the **tidyverse** and data frames are expected to be converted as tibbles. You may either wish to download and save the files into a directory and to read them into R from there, or you may equally pass the address to `read_csv()` which will read the dataset from remote.

### Answer the following questions using R {.unnumbered}

1.  Load into R the dataset `sheep.csv` available [here](https://raw.githubusercontent.com/acarpignani/notebook/main/datasets/sheep.csv) and store it into a variable named `sheep`. Using `summarise()` find the mean weight and height of the sheep. Using the function `lm` find the regression line of the weight against the height of the sheep. \
    **Tip.** The `lm` function has the following syntax: `lm(outcome ~ predictor, data = mydata)`.
2.  Load into R the dataset `01test.csv` available [here](https://raw.githubusercontent.com/acarpignani/notebook/main/datasets/01test.csv) and store it into a variable named `cuboids`. The data represents the three dimensions of a set of cuboids. Add a column `volume` with the volume ($V = xyz$) of all these cuboids. Filter for the cuboids with a volume smaller then or equal to 40,000. Calculate the average volume of the full dataset.
3.  Load the dataset `cells.csv` available [here](https://raw.githubusercontent.com/acarpignani/notebook/main/datasets/cells.csv) and store it into a variable named `cells`. Change the variables `age`, `sex` and `weight` into factors. Run the `summary()` function on the modified dataset.
4.  Load the dataset `pressure.csv` available [here](https://raw.githubusercontent.com/acarpignani/notebook/main/datasets/pressure.csv) and store it into a variable named `pressure`. Change the type of the columns `sex` and `smoker` to factor. Use the function `separate()` to split the column `blood_pressure` into two new columns `sys` (for systolic) and `dia` (for diastolic). Then convert the columns `sys` and `dia` into numbers using the function `as.double()`. Group the dataset by `sex` and `smoker` and calculate the average systolic and diastolic pressure by sex and smoker status.
5.  Load the dataset `worms.csv` available [here](https://raw.githubusercontent.com/acarpignani/notebook/main/datasets/worms.csv) and store it into a variable named `worms`. Use the function `clean_names()` from the package `janitor` (install it, if you haven't done it yet), to standardise the names of the columns. Convert the `vegetation` column to factor. Using the function `str_replace()` to replace the `.` sign in the `field_name` with a white space. \
    **Tip.** You need to be extra careful here because the sign `.` is actually a *reprex* so if you attempt substitute the pattern `"."` with replacement `" "` you'll get something quite unexpected. To pass the symbol `.` as such you need to wrap it into square brackets.
