# Practice 1: Introduction to R programming

The questions below should be straightforward if you have reviewed the lectures: do not expect here anything particularly challenging yet. This should only be a review to make sure you have understood everything so far. In further practice sessions and projects we will encounter more challenging (and fun) activities.

## Simple questions

### Answer the following questions using R

1.  Generate a vector that contains the numbers from 1 to 10, and concatenate its reversed vector (i.e. the vector with the same numbers in descending order), obtaining a vector with 20 elements.\
    **Tip.** You may wish to check the documentation of the function `sort()`.

2.  Set the seed to `101` and generate a vector that contains 20 random numbers between 0 and 1 using the function `runif()`. Replace the 10 central values (i.e. the values in positions 5 to 15) with their corresponding squares. Round the final vector to three decimal places.

3.  Create a vector called `stock_prices` with the following data points: 23, 27, 23, 21, 34. Assign names to the price data points relating to the day of the week, starting with `Mon`, `Tue`, `Wed`, etc. Calculate the average (mean) and the standard deviation of the stock price for the week.

4.  Create a vector called `over_23` consisting of logical values that correspond to the days where the stock price in Question 3 was greater than \$23. Use the over_23 vector to filter out the stock_prices vector and only return the day and prices where the price was greater than \$23.

5.  Still referring to the vector in Question 3, use a built-in function to find the day the price was the highest stock price. Also find the *range* of the stock price for the week.\
    **Tip.** Remember that the range is defined in maths as the difference between the maximum and the minimum values, however, the function `range()` does not give this result, but...

6.  Set the seed to `123` and generate 100 random numbers from a normal distribution with mean 10 and standard deviation 2. State the highest and the lowest number for this sequence.

7.  We wish to simulate 100 trials of coin flipping with a fair coin. Outcome of the simulation should be a vector `fair_outcome` with 100 values. Each value should be one of the two logical values `TRUE` and `FALSE`, depending on whether the coin has landed head-up (= true) or tails-up (= false). Set the seed `101` and run the simulation.

8.  Change the previous code to adapt to a biased coin which lands head-up 2/3 of the times and tails-up only 1/3. Set again the seed to `101` to run the simulation and store the result into the vector `biased_outcome`.

9.  Referring to the previous two questions, create two new vectors, `fair_count` and `biased_count` containing the number of heads and tails in the two simulations.\
    **Tip.** You may wish to use the fact that logical values can be treated as 0's and 1's by R.

10. Run a simulation for the length (in cm) and the width (in cm) of a table.

    -   Set the seed to `123` and create a vector `length` with 10 random vectors extracted from a normal distribution with mean 100 and standard deviation 5.
    -   Set the seed to `234` and create a vector `width` with 10 random vectors extracted from a normal distribution with mean 60 and standard deviation 5.
    -   Create the vector `area` by multiplying together each entry of `length` with the corresponding entry of `width`, and calculate the mean and the standard deviation of this new vector. What is the standard deviation of `area`?

## Challenging questions

1.  Create the vector called `heights` with the following data points: 155, 165, 172, 123, 168, 182, 177, 159, 163, 167. Calculate the mean and the standard deviation of the vector `height`. A **outlier** is a value that differs from the mean, $\bar{x}$, more than two times the standard deviation, $s_x$. Establish whether the vector `heights` has any outliers.

2.  Set the seed to `111` and create a vector, `x`, with 100 random numbers extracted from a standard normal distribution ($\mu = 0$, $\sigma^2 = 1$). Calculate the mean and the standard deviation of this vector. Transform the vector using the formula $y = 25x + 150$. Calculate the mean and the standard deviation of the vector `y`.

3.  To approximate $\pi$ we can use a Monte Carlo simulation. The idea of the simulation is to take $n$ random points in the square of side $2$ and calculate the percentage of the number of points that fall inside the circle with radius $1$ inscribed in the square.

    -   Set the seed to `111` and generate 1000 random numbers between -1 and 1 and call the vector `x`. (Extract the sample using the uniform distribution.)
    -   Set the seed to `101` and generate other 1000x random numbers between -1 and 1 and call the vector `y`.
    -   Calculate the proportion of how many points with coordinates $(x,y)$ are in the circle with centre $(0,0)$ and radius $1$ and multiply this number by $4$. (Why?)
    -   Repeat the simulation with 10,000, 100,000 and 1,000,000 values.
    -   What do you notice?
